service: institutebot
provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1
  iamRoleStatements:
      - Effect: "Allow"
        Action:
          - cloudwatchlogs:*
          - logs:*
          - dynamodb:*
        Resource: "*"
functions:
  - ${file(institutebot.yml)}
